ScheduleSystem/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='/account/login/')),
    path('account/', include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('timesheet/', include('timesheets.urls')),
    path('subjects/', include('subjects.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

accounts/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('login/', user_login, name='login'),
    path('logout/', user_logout, name='logout'),
]

subjects/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('', ViewSubjects.as_view(), name='subjects'),
    path('<int:pk>/', ViewSubjectDetail.as_view(), name='subject_detail'),
]

subjects/models.py
from django.db import models
from django.urls import reverse


class Subject(models.Model):
    name = models.CharField(verbose_name='Название предмета', max_length=50, null=False, blank=False)
    hours = models.IntegerField(verbose_name='Часы', null=False, blank=False)
    image = models.ImageField(upload_to='subjects_images/', default='subjects_images/default.jpg')

    id_group = models.ForeignKey(
        'timesheets.Group',
        verbose_name='Номер группы',
        on_delete=models.PROTECT,
        null=False,
        blank=False
    )
    id_teacher = models.ForeignKey(
        'timesheets.Teacher',
        verbose_name='Преподаватель',
        on_delete=models.PROTECT,
        null=False,
        blank=False
    )

    exam_form_choices = [
        ('ex', 'Экзамен'),
        ('zch', 'Зачет'),
        ('zo', 'Зачет с оценкой'),
        ('kr', 'Курсовая работа'),
    ]
    exam_form = models.CharField(
        verbose_name='Экзаменационная форма',
        max_length=20,
        choices=exam_form_choices,
        null=False,
        blank=False
    )

    num_cub = models.IntegerField(verbose_name='Кабинет', null=True, blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('subject_detail', kwargs={"pk": self.pk})

    class Meta:
        verbose_name = 'Предмет'
        verbose_name_plural = 'Предметы'
        ordering = ['name']

subjects/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView

from subjects.models import *


class ViewSubjects(LoginRequiredMixin, ListView):
    model = Subject
    template_name = 'subjects/subjects_list.html'
    context_object_name = 'subjects'

    def get_queryset(self):
        return Subject.objects.filter(id_group=self.request.user.student.id_group)


class ViewSubjectDetail(DetailView):
    model = Subject
    template_name = 'subjects/subject_detail.html'
    context_object_name = 'subject'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['subjects'] = Subject.objects.filter(id_group=self.request.user.student.id_group)

        return context

subjects/templates/subjects/subject_detail.html
{% extends 'subjects/subjects_list.html' %}

{% block subject_detail %}
    <div class="card-header">
        <h5>{{ subject.name }}</h5>
    </div>
    <div class="card-body">
        <p class="card-text">
            <span class="subtitle"><i class="fa-solid fa-chalkboard-user"></i> Преподаватель:</span>
            {{ subject.id_teacher }}
        </p>
        <p class="card-text">
            <span class="subtitle"><i class="fa-solid fa-hashtag"></i> Номер кабинета:</span>
            {{ subject.hours }}
        </p>
        <p class="card-text">
            <span class="subtitle"><i class="fa-regular fa-clock"></i> Время занятия:</span>
            {{ subject.num_cub }}
        </p>
        <p class="card-text">
            <span class="subtitle"><i class="fa-regular fa-star"></i> Экзаменационная форма:</span>
            {{ subject.get_exam_form_display }}
        </p>
    </div>
{% endblock %}

subjects/templates/subjects/subjects_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Предметы
{% endblock %}

{% block static %}
    <link href="{% static 'css/subjects_list.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="container mt-5">
        <h3><i class="fa-regular fa-calendar-days"></i>Предметы</h3>
        <div class="d-flex justify-content-start">
            <div class="list-group d-flex flex-column w-25">

                {% for item in subjects %}
                    <a aria-current="true" href="{{ item.get_absolute_url }}" class="list-group-item mb-3"
                       style="background-image: url({{ item.image.url }})">
                        <b>{{ item.name }}</b><br>
                        {{ item.id_teacher }}
                    </a>
                {% endfor %}
            </div>

            <div class="card subject-detail ms-4 w-50">
                {% block subject_detail %}
                    <div class="card-body">
                        <h5 class="card-title">
                            {% if subjects|length > 0 %}
                                Выберите занятие
                            {% else %}
                                Сегодня занятий нет
                            {% endif %}
                        </h5>
                    </div>
                {% endblock %}
            </div>
        </div>
    </div>
{% endblock %}

subjects/templates/subjects/view_subject.html
{% extends 'subjects/subjects_list.html' %}

{% block subject_detail %}
    <div class="card-header">
        <h5>{{ subject.name }}</h5>
    </div>
    <div class="card-body">
        <p class="card-text">
            <span class="subtitle"><i class="fa-solid fa-chalkboard-user"></i> Преподаватель:</span>
            {{ subject.id_teacher }}
        </p>
        <p class="card-text">
            <span class="subtitle"><i class="fa-solid fa-hashtag"></i> Номер кабинета:</span>
            {{ subject.hours }}
        </p>
        <p class="card-text">
            <span class="subtitle"><i class="fa-regular fa-clock"></i> Время занятия:</span>
            {{ subject.num_cub }}
        </p>
        <p class="card-text">
            <span class="subtitle"><i class="fa-regular fa-clock"></i> Экзаменационная форма:</span>
            {{ subject.get_exam_form_display }}
        </p>
    </div>
{% endblock %}